name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt-get install musl-tools
    - run: make PROG=esputil_linux CC=musl-gcc CFLAGS="-static -s -Os"
    - uses: actions/upload-artifact@v3
      with:
        path: esputil_linux
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - run: make PROG=esputil_macos
    - uses: actions/upload-artifact@v3
      with:
        path: esputil_macos
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: make esputil.exe
    - uses: actions/upload-artifact@v3
      with:
        path: esputil.exe
  release:
    needs: [linux, macos, windows]
    runs-on: macos-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
    - run: find . -ls
    - uses: softprops/action-gh-release@v1
      with:
        tag_name: 1.0.0
        files: |
          esputil.exe
          esputil_linux
          espuil_macos
