name: build
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install packages
      run: sudo apt-get install musl-tools
    - name: build
      run: make PROG=esputil_linux CC=musl-gcc CFLAGS="-static -s -Os"
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: esputil_linux
        path: esputil_linux
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make PROG=esputil_macos
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: esputil_macos
        path: esputil_macos
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: make esputil.exe
    - name: upload
      uses: actions/upload-artifact@v3
      with:
        name: esputil.exe
        path: esputil.exe
  release:
    needs: [linux, macos, windows]
    runs-on: macos-latest
    steps:
    -name: download
      uses: actions/download-artifact@v3
      with:
        path: |
          esputil.exe
          esputil_linux
          espuil_macos
    - name: upload
      uses: softprops/action-gh-release@v1
      with:
        tag_name: 1.0.0
        files: |
          esputil.exe
          esputil_linux
          espuil_macos
